# @package _global_
defaults:
  - _self_

target: adoption
task: classification

num_classes: 5
weights:
live_loading: True  # whether to load images from a list of paths (instead of a list of .pt)
delete_segmentation: False  # whether to delete the first channel of a three channel image
balanced_accuracy: False
eval_metric: acc
data_orig:
img_size: 225  # target size of image-resize
one_hot: True  # whether to operate one-hot encoding on categorical features
corruption_rate: 0.1

field_lengths_tabular: None   # must be a path

labels_train: /root/autodl-tmp/PetFinder_datasets/dataset/petfinder_adoptionprediction/dataset_train.pt
labels_val: /root/autodl-tmp/PetFinder_datasets/dataset/petfinder_adoptionprediction/dataset_valid.pt


data_train_tabular: /root/autodl-tmp/PetFinder_datasets/dataset/petfinder_adoptionprediction/dataset_train.csv
data_val_tabular: /root/autodl-tmp/PetFinder_datasets/dataset/petfinder_adoptionprediction/dataset_valid.csv
data_test_eval_tabular: /root/autodl-tmp/PetFinder_datasets/dataset/petfinder_adoptionprediction/dataset_test.csv

data_train_imaging: /root/autodl-tmp/PetFinder_datasets/dataset/petfinder_adoptionprediction/train_image
data_val_imaging: /root/autodl-tmp/PetFinder_datasets/dataset/petfinder_adoptionprediction/val_image
data_test_eval_imaging: /root/autodl-tmp/PetFinder_datasets/dataset/petfinder_adoptionprediction/test_image

# 用作 evaluate 的数据集
data_train_eval_imaging: /root/autodl-tmp/PetFinder_datasets/raw_dataset/petfinder_adoptionprediction/train_images
labels_train_eval_imaging: 