# @package _global_
defaults:
  - _self_

target: anime
task: regression

num_classes: 1
weights:
live_loading: True  # whether to load images from a list of paths (instead of a list of .pt)
delete_segmentation: False  # whether to delete the first channel of a three channel image
balanced_accuracy: False
eval_metric: rmse
data_orig:
img_size: 224  # target size of image-resize
one_hot: True  # whether to operate one-hot encoding on categorical features
corruption_rate: 0.1

low_data_splits: ['']

# num of features
num_cat: 5
num_con: 6

labels_train: /mnt/hdd/jiazy/anime/features/train_labels.pt
labels_val: /mnt/hdd/jiazy/anime/features/val_labels.pt

data_train_imaging: /mnt/hdd/jiazy/anime/features/train_paths.pt
data_val_imaging: /mnt/hdd/jiazy/anime/features/val_paths.pt


data_train_tabular: /mnt/hdd/jiazy/anime/features/train_features.csv
data_val_tabular: /mnt/hdd/jiazy/anime/features/val_features.csv

field_lengths_tabular: /mnt/hdd/jiazy/anime/features/tabular_lengths.pt


data_train_eval_tabular: /mnt/hdd/jiazy/anime/features/train_features.csv
labels_train_eval_tabular: /mnt/hdd/jiazy/anime/features/train_labels.pt

data_val_eval_tabular: /mnt/hdd/jiazy/anime/features/val_features.csv
labels_val_eval_tabular: /mnt/hdd/jiazy/anime/features/val_labels.pt

data_test_eval_tabular: /mnt/hdd/jiazy/anime/features/test_features.csv
labels_test_eval_tabular: /mnt/hdd/jiazy/anime/features/test_labels.pt


data_train_eval_imaging: /mnt/hdd/jiazy/anime/features/train_paths.pt
labels_train_eval_imaging: /mnt/hdd/jiazy/anime/features/train_labels.pt

data_val_eval_imaging: /mnt/hdd/jiazy/anime/features/val_paths.pt
labels_val_eval_imaging: /mnt/hdd/jiazy/anime/features/val_labels.pt

data_test_eval_imaging: /mnt/hdd/jiazy/anime/features/test_paths.pt
labels_test_eval_imaging: /mnt/hdd/jiazy/anime/features/test_labels.pt