# @package _global_
defaults:
 - _self_

target: breast_cancer
task: classification

num_classes: 4
weights:
live_loading: True  # whether to load images from a list of paths (instead of a list of .pt)
delete_segmentation: False  # whether to delete the first channel of a three channel image
balanced_accuracy: False
eval_metric: acc
data_orig:
low_data_splits: ['']
img_size: 224  # target size of image-resize
one_hot: True  # whether to operate one-hot encoding on categorical features
corruption_rate: 0.1

# num of features
num_cat: 5
num_con: 1

labels_train: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/train_labels.pt
labels_val: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/val_labels.pt

data_train_imaging: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/train_paths.pt
data_val_imaging: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/val_paths.pt

# data_train_imaging: train_images_all_views.pt
# data_val_imaging: val_images_all_views.pt

data_train_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/train_features_TIP.csv
data_val_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/val_features_TIP.csv

field_lengths_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/tabular_lengths.pt


data_train_eval_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/train_features_TIP.csv
labels_train_eval_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/train_labels.pt

data_val_eval_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/val_features_TIP.csv
labels_val_eval_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/val_labels.pt

data_test_eval_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/test_features_TIP.csv
labels_test_eval_tabular: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/test_labels.pt


data_train_eval_imaging: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/train_paths.pt
labels_train_eval_imaging: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/train_labels.pt

data_val_eval_imaging: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/val_paths.pt
labels_val_eval_imaging: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/val_labels.pt

data_test_eval_imaging: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/test_paths.pt
labels_test_eval_imaging: /data1/jiazy/tab_image_bench/cbis-ddsm-breast-cancer-image-dataset/features/test_labels.pt